spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${services.keycloak.url}/realms/${services.keycloak.realm}/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: authentication
          uri: ${services.keycloak.url}
          predicates:
            - Path=/openid-connect/**
          filters:
            - RewritePath=/openid-connect,/realms/${services.keycloak.realm}/protocol/openid-connect

        - id: portal
          uri: lb://portal-service
          predicates:
            - Path=/portal/**
          filters:
            - RewritePath=/portal,/

        - id: logist
          uri: lb://logist-service
          predicates:
            - Path=/logist/**
          filters:
            - RewritePath=/logist,/

        - id: driver
          uri: lb://driver-service
          predicates:
            - Path=/driver/**
          filters:
            - RewritePath=/driver,/

        - id: dwh
          uri: lb://dwh-service
          predicates:
            - Path=/dwh/**
          filters:
            - RewritePath=/dwh,/

    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${services.registry.host}:${services.registry.port}/eureka/
  instance:
    prefer-ip-address: true

services:
  keycloak:
    url: http://localhost:8080
    realm: apprealm
    client: app-client
    client-secret: G9RVUvss9ctgzIdTggncqknKzCG1MxQN
    username: admin
    password: qwe123
  registry:
    host: localhost
    port: 8761

server:
  port: 8081